apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: <your-ebs-volume-id>
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain

