apiVersion: v1
kind: Service
metadata:
  name: example-headless
spec:
  clusterIP: None
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-statefulset
spec:
  serviceName: example-headless
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: web
        image: nginx:latest
        volumeMounts:
        - name: storage
          mountPath: "/usr/share/nginx/html"
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
